name: mCLM
channels:
  - anaconda
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.1.31=hbcca054_0
  - cairo=1.18.0=hebfffa5_3
  - certifi=2025.1.31=pyhd8ed1ab_0
  - chardet=5.2.0=py311h38be061_2
  - contourpy=1.3.1=py311hd18a35c_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - cyrus-sasl=2.1.27=h54b06d7_7
  - expect=5.45.4=h555a92e_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.55.0=py311h2dc5d0c_0
  - freetype=2.12.1=h267a509_2
  - freetype-py=2.3.0=pyhd8ed1ab_0
  - git-lfs=3.5.1=h06a4308_0
  - greenlet=3.1.1=py311hfdbb021_0
  - icu=75.1=he02047a_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.7=py311hd18a35c_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.43=h712a8e2_2
  - lerc=4.0.0=h27087fc_0
  - libblas=3.9.0=25_linux64_openblas
  - libboost=1.86.0=hb8260a3_2
  - libboost-python=1.86.0=py311h5b7b71f_2
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcblas=3.9.0=25_linux64_openblas
  - libdeflate=1.22=hb9d3cd8_0
  - libedit=3.1.20191231=he28a2e2_2
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libglib=2.82.2=h2ff4ddf_0
  - libgomp=14.2.0=h77fa898_1
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=25_linux64_openblas
  - libnsl=2.0.1=hd590300_0
  - libntlm=1.4=h7f98852_1002
  - libopenblas=0.3.28=pthreads_h94d23a6_1
  - libpng=1.6.44=hadc24fc_0
  - libpq=17.2=h04577a9_0
  - librdkit=2024.09.2=h84b0b3c_1
  - libsqlite=3.47.0=hadc24fc_1
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libtiff=4.7.0=he137b08_1
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - matplotlib-base=3.9.2=py311h2b939e6_2
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.5=he02047a_1
  - neo4j-python-driver=5.28.1=pyhd8ed1ab_0
  - numpy=2.1.3=py311h71ddf71_0
  - openjpeg=2.5.2=h488ebb8_0
  - openldap=2.6.8=hedd0468_0
  - openssl=3.4.1=h7b32b05_0
  - packaging=24.2=pyhff2d567_1
  - pandas=2.2.2=py311h14de704_1
  - pcre2=10.44=hba22ea6_2
  - pillow=11.0.0=py311h49e9ac3_0
  - pip=24.3.1=pyh8b19718_0
  - pixman=0.43.2=h59595ed_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pycairo=1.27.0=py311h124c5f0_0
  - pyparsing=3.2.0=pyhd8ed1ab_1
  - python=3.11.10=hc5c86c4_3_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_0
  - python-tzdata=2024.2=pyhd8ed1ab_0
  - python_abi=3.11=5_cp311
  - pytz=2024.2=pyhd8ed1ab_0
  - qhull=2020.2=h434a139_5
  - readline=8.2=h8228510_1
  - reportlab=4.2.5=py311h9ecbd09_0
  - rlpycairo=0.2.0=pyhd8ed1ab_0
  - setuptools=75.6.0=pyhff2d567_1
  - six=1.16.0=pyh6c4a22f_0
  - sqlalchemy=2.0.36=py311h9ecbd09_0
  - tk=8.6.13=noxft_h4845f30_101
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - tzdata=2024b=hc8b5060_0
  - unicodedata2=15.1.0=py311h9ecbd09_1
  - wheel=0.45.1=pyhd8ed1ab_0
  - xorg-libice=1.1.1=hb9d3cd8_1
  - xorg-libsm=1.2.4=he73a12e_1
  - xorg-libx11=1.8.10=h4f16b4b_0
  - xorg-libxau=1.0.11=hb9d3cd8_1
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxrender=0.9.11=hb9d3cd8_1
  - xorg-xorgproto=2024.1=hb9d3cd8_1
  - xz=5.2.6=h166bdaf_0
  - zip=3.0=hd590300_3
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
    - datasets==3.3.2
    - dgl==2.4.0+cu121
    - dgllife==0.3.2
    - hydra-core==1.3.2
    - igraph==0.11.8
    - lightning==2.5.0
    - lightning-bolts==0.7.0
    - peft==0.11.0
    - rdkit==2024.9.6
    - safetensors==0.5.2
    - seaborn==0.13.2
    - torch-geometric==2.6.1
    - torchdata==0.11.0
    - tqdm==4.67.1
    - transformers==4.51.3
    - wandb==0.19.8

