name: mCLM
channels:
  - pytorch
  - pyg
  - dglteam/label/th23_cu121
  - nvidia
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - annotated-types=0.7.0=pyhd8ed1ab_0
  - anyio=4.6.2.post1=pyhd8ed1ab_0
  - arrow=1.3.0=pyhd8ed1ab_0
  - backoff=2.2.1=pyhd8ed1ab_0
  - beautifulsoup4=4.12.3=pyha770c72_0
  - blessed=1.19.1=pyhe4f9e05_2
  - boto3=1.35.47=pyhd8ed1ab_0
  - botocore=1.35.47=pyge310_1234567_0
  - brotli-python=1.1.0=py311hfdbb021_2
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2024.8.30=hbcca054_0
  - cachecontrol=0.14.0=pyhd8ed1ab_1
  - cachecontrol-with-filecache=0.14.0=pyhd8ed1ab_1
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.17.1=py311hf29c0ef_0
  - charset-normalizer=3.4.0=pyhd8ed1ab_0
  - cleo=2.1.0=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - crashtest=0.4.1=pyhd8ed1ab_0
  - croniter=1.4.1=pyhd8ed1ab_0
  - cryptography=43.0.3=py311hafd3f86_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.6.77=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.6=3
  - dateutils=0.6.12=py_0
  - dbus=1.13.6=h5008d03_3
  - deepdiff=7.0.1=pyhd8ed1ab_0
  - dgl=2.4.0.th23.cu121=py311_0
  - distlib=0.3.9=pyhd8ed1ab_0
  - dnspython=2.7.0=pyhff2d567_0
  - dulwich=0.21.7=py311h9ecbd09_1
  - email-validator=2.2.0=pyhd8ed1ab_0
  - email_validator=2.2.0=hd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - expat=2.6.3=h5888daf_0
  - fastapi=0.115.3=pyhd8ed1ab_0
  - fastapi-cli=0.0.5=pyhd8ed1ab_1
  - filelock=3.16.1=pyhd8ed1ab_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.1.5=py311h0f6cedb_2
  - h11=0.14.0=pyhd8ed1ab_0
  - h2=4.1.0=pyhd8ed1ab_0
  - hpack=4.0.0=pyh9f0ad1d_0
  - httpcore=1.0.6=pyhd8ed1ab_0
  - httptools=0.6.1=py311h9ecbd09_1
  - httpx=0.27.2=pyhd8ed1ab_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - idna=3.10=pyhd8ed1ab_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - importlib_resources=6.4.5=pyhd8ed1ab_0
  - inquirer=3.1.4=pyhd8ed1ab_0
  - itsdangerous=2.2.0=pyhd8ed1ab_0
  - jaraco.classes=3.4.0=pyhd8ed1ab_1
  - jeepney=0.8.0=pyhd8ed1ab_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - jmespath=1.0.1=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - keyring=24.3.1=pyha804496_1
  - ld_impl_linux-64=2.43=h712a8e2_2
  - libabseil=20240116.2=cxx17_he02047a_1
  - libblas=3.9.0=25_linux64_openblas
  - libcblas=3.9.0=25_linux64_openblas
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.11.1.6=0
  - libcurand=10.3.7.77=0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libexpat=2.6.3=h5888daf_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran-ng=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libglib=2.82.2=h2ff4ddf_0
  - libgomp=14.2.0=h77fa898_1
  - libiconv=1.17=hd590300_2
  - liblapack=3.9.0=25_linux64_openblas
  - libnpp=12.0.2.50=0
  - libnsl=2.0.1=hd590300_0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libopenblas=0.3.28=pthreads_h94d23a6_0
  - libprotobuf=4.25.3=hd5b35b9_1
  - libsqlite=3.47.0=hadc24fc_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libtorch=2.1.2=cpu_generic_h0ec3652_4
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.49.2=hb9d3cd8_0
  - libzlib=1.3.1=hb9d3cd8_2
  - lightning=2.1.2=pyhd8ed1ab_0
  - lightning-cloud=0.5.70=pyhd8ed1ab_0
  - lightning-utilities=0.11.8=pyhd8ed1ab_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.2=py311h2dc5d0c_0
  - mdurl=0.1.2=pyhd8ed1ab_0
  - more-itertools=10.5.0=pyhd8ed1ab_0
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_0
  - msgpack-python=1.1.0=py311hd18a35c_0
  - ncurses=6.5=he02047a_1
  - networkx=3.3=pyhd8ed1ab_1
  - nomkl=1.0=h5ca1d4c_0
  - numpy=1.26.4=py311h64a7726_0
  - openssl=3.3.2=hb9d3cd8_0
  - ordered-set=4.1.0=pyhd8ed1ab_0
  - orjson=3.10.10=py311h9e33e62_0
  - packaging=24.1=pyhd8ed1ab_0
  - pcre2=10.44=hba22ea6_2
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pip=24.2=pyh8b19718_1
  - pkginfo=1.11.2=pyhd8ed1ab_0
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - poetry=1.8.4=linux_pyha804496_0
  - poetry-core=1.9.1=pyhd8ed1ab_0
  - poetry-plugin-export=1.8.0=pyhd8ed1ab_0
  - protobuf=4.25.3=py311hbffca5d_1
  - psutil=6.0.0=py311h9ecbd09_2
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pydantic=2.1.1=pyhd8ed1ab_0
  - pydantic-core=2.4.0=py311h46250e7_0
  - pyg=2.4.0=py311_torch_2.1.0_cu121
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyjwt=2.9.0=pyhd8ed1ab_1
  - pyparsing=3.2.0=pyhd8ed1ab_1
  - pyproject_hooks=1.2.0=pyh7850678_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.11.5=hab00c5b_0_cpython
  - python-build=1.2.2.post1=pyhff2d567_0
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-dotenv=1.0.1=pyhd8ed1ab_0
  - python-editor=1.0.4=pyhd8ed1ab_1
  - python-fastjsonschema=2.20.0=pyhd8ed1ab_0
  - python-installer=0.7.0=pyhd8ed1ab_0
  - python-multipart=0.0.14=pyhff2d567_0
  - python_abi=3.11=5_cp311
  - pytorch-cuda=12.1=ha16c6d3_6
  - pytz=2024.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py311h9ecbd09_1
  - rapidfuzz=3.10.0=py311hfdbb021_0
  - readchar=4.2.0=pyhd8ed1ab_0
  - readline=8.2=h8228510_1
  - requests=2.32.3=pyhd8ed1ab_0
  - requests-toolbelt=1.0.0=pyhd8ed1ab_0
  - rich=13.9.3=pyhd8ed1ab_0
  - s3transfer=0.10.3=pyhd8ed1ab_0
  - scikit-learn=1.5.0=py311he08f58d_1
  - scipy=1.13.1=py311h517d4fd_0
  - secretstorage=3.3.3=py311h38be061_3
  - setuptools=75.1.0=pyhd8ed1ab_0
  - shellingham=1.5.4=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - sleef=3.7=h1b44611_0
  - sniffio=1.3.1=pyhd8ed1ab_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - starlette=0.41.0=pyhd8ed1ab_0
  - starsessions=1.3.0=pyhd8ed1ab_0
  - sympy=1.13.3=pypyh2585a3b_103
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tk=8.6.13=noxft_h4845f30_101
  - tomli=2.0.2=pyhd8ed1ab_0
  - tomlkit=0.13.2=pyha770c72_0
  - torchmetrics=1.4.0.post0=pyhd8ed1ab_0
  - tqdm=4.66.5=pyhd8ed1ab_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - trove-classifiers=2024.10.21.16=pyhd8ed1ab_0
  - typer=0.12.5=pyhd8ed1ab_0
  - typer-slim=0.12.5=pyhd8ed1ab_0
  - typer-slim-standard=0.12.5=hd8ed1ab_0
  - types-python-dateutil=2.9.0.20241003=pyhff2d567_0
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - urllib3=2.2.3=pyhd8ed1ab_0
  - uvicorn=0.32.0=py311h38be061_0
  - uvicorn-standard=0.32.0=h38be061_0
  - uvloop=0.21.0=py311h9ecbd09_0
  - virtualenv=20.27.0=pyhd8ed1ab_0
  - watchfiles=0.24.0=py311h9e33e62_1
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - websocket-client=1.8.0=pyhd8ed1ab_0
  - websockets=12.0=py311h459d7ec_0
  - wheel=0.44.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - zipp=3.20.2=pyhd8ed1ab_0
  - zstandard=0.23.0=py311hbc35293_1
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - absl-py==2.1.0
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.10
      - aiosignal==1.3.1
      - antlr4-python3-runtime==4.9.3
      - appdirs==1.4.4
      - attrs==24.2.0
      - cloudpickle==3.1.0
      - contourpy==1.3.0
      - cramjam==2.9.0
      - cycler==0.12.1
      - datasets==2.19.1
      - dgllife==0.3.2
      - dill==0.3.8
      - docker-pycreds==0.4.0
      - fastparquet==2024.5.0
      - fonttools==4.54.1
      - frozenlist==1.5.0
      - fsspec==2024.3.1
      - future==1.0.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - grpcio==1.67.0
      - huggingface-hub==0.26.1
      - hydra-core==1.3.2
      - hyperopt==0.2.7
      - kiwisolver==1.4.7
      - lightning-bolts==0.7.0
      - markdown==3.7
      - matplotlib==3.8.3
      - multidict==6.0.5
      - multiprocess==0.70.16
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.6.77
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - pandas==2.2.2
      - pillow==11.0.0
      - propcache==0.2.0
      - py4j==0.10.9.7
      - pyarrow==16.1.0
      - pyarrow-hotfix==0.6
      - pytorch-lightning==1.9.5
      - rdkit==2023.3.2
      - regex==2024.9.11
      - safetensors==0.4.5
      - sentry-sdk==2.17.0
      - setproctitle==1.3.3
      - smmap==5.0.1
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - tokenizers==0.19.1
      - torch==2.3.1
      - torch-scatter==2.1.2
      - torchaudio==2.3.1
      - torchdata==0.7.1
      - torcheval==0.0.7
      - torchsampler==0.1.2
      - torchvision==0.18.1
      - transformers==4.46.3
      - triton==2.3.1
      - tzdata==2024.2
      - wandb==0.16.4
      - werkzeug==3.0.4
      - xxhash==3.5.0
      - yarl==1.16.0
prefix: /home/edwarc24/miniforge3/envs/mCLM
